[project]
name = "quarryng"
version = "0.1.0"
description = "Quarry but with protodef."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=44.0.2",
    "mutf8>=1.0.6",
    "twisted>=24.11.0",
]

[tool.setuptools.package-data]
"quarryng" = ["data/minecraft-data/**"]